### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by eternaleclipse** [AlexAltea/capstone.js#16]

**Comment by AlexAltea** [comment]
That is clarified now via ddb12e8166c7ddb1f19546d6ea9e6d1e7a3b1172. The bindings are released under the usual BSD 3-clause license terms:
https://github.com/AlexAltea/capstone.js/blob/master/LICENSE

Capstone itself (and is underlying dependency, LLVM) are both released under BSD 3-clause licenses as well.
