### ISSUE TITLE
Library not in npm registry

### ISSUE THREAD

**Issue by CypElf** [AlexAltea/capstone.js#18]
It would be nice to have this library available through npm.
The dependency to this library would be easier to manage with front end frameworks already using npm, but more importantly, it could be used in node.js where it's currently very complicated to integrate this library.

**Comment by AlexAltea** [comment]
The only purpose of Capstone.js is to have Capstone run in browsers, not in Node.js environments.

I have intentionally avoided publishing this package to NPM because https://www.npmjs.com/package/capstone already exists, and is a much better way to run Capstone in Node.js environments.

**Comment by CypElf** [comment]
It hasn't received updates since 5 years now, it doesn't seem to be supported anymore unfortunately.
The node.js version supported by this other project is very old and has installation issues with node.js' latest LTS, making it basically useless and unusable.
So I don't really understand why because this other library exists you don't want to publish yours on npm.

**Comment by AlexAltea** [comment]
Done at https://www.npmjs.com/package/@alexaltea/capstone-js

**Comment by CypElf** [comment]
For some reason, node doesn't find the module when imported using a require, even if installed using npm. I've never seen that before, what could be the issue?

**Comment by AlexAltea** [comment]
No idea, I have not much experience with Node, and no time to debug it at the moment.

Feel free to open another issue to keep track of this!
