### ISSUE TITLE
Can't include the library in node.js after installing it with npm

### ISSUE THREAD

**Issue by CypElf** [AlexAltea/capstone.js#19]
The following line, in node.js, after successfully npm installing the package `@alexaltea/capstone-js` :
```js
const cs = require("@alexaltea/capstone-js")
```

results in an error :
```
Error: Cannot find module '@alexaltea/capstone-js'
```

**Comment by AlexAltea** [comment]
I might be wrong, but I suspect the underlying reason for this is that Emscripten modules (in our case `MCapstone`) is not compatible with Node modules (CommonJS).

Some extra glue might be needed, but I don't have neither time nor experience with Node.js to make it happen.
PRs would be very welcome here.

**Comment by CypElf** [comment]
I will probably take a deeper look at it some time soon when I have enough time to work a bit on that. Will open a PR when done.
