### ISSUE TITLE
Memory limit

### ISSUE THREAD

**Issue by userlandkernel** [AlexAltea/capstone.js#9]
When disassembling with capstone it throws the error that it cannot grow memory further because it exceeded the compiletime limit.

I passed the flag -s ALLOW_MEMORY_GROWTH=1 in build.py and recompiled the project

After that it said "MCapstone.ccall is undefined"

Thus I added the flag to export  that symbol as explained on emscripten and it works fine.

However the code now runs in the browser without any errors but seems to fail each time trying to disassemble something.

Can anyone here help me get it to compile without having the default memory boundaries?

**Comment by AlexAltea** [comment]
Messages such as `MCapstone.ccall is undefined` happen whenever the module is loaded asynchronously, because our wrapper will call the function `ccall` which might not be created yet. This happens for a variety of reasons (e.g. either because WASM is enabled, or because a separate memory file has been generated that needs to be asynchronously loaded).

One temporary solution is to explicitly disable any parameter that might create asynchronously-loaded modules, i.e. passing `-s WASM=0 --memory-init-file 0`. However, the proper solution would be to make sure or wrapper also works when the module is loaded asynchronously.

I had planned to fix this issue, as well as update Capstone.js to 4.x (our versioning matches Capstone's one), and fix #8. I'll take care of that next week.

**Comment by userlandkernel** [comment]
Hi AlexaAltea, thanks for responding this quick.
Some functions were deprecated and enscriptem doesn't by default export ccall.
I fixed it and its compiled and running well with no memory limit anymore.
Disassembles my mach-os like a charm.
You can see my project here at https://github.com/userlandkernel/GandalfsMachotool.
If you want I'll include a license and reference to your work and create a fork of your project updating it for modern emscripten.

**Comment by AlexAltea** [comment]
@userlandkernel Oh, really cool project! And sure, I'll be glad if you refer to this project. :-)

> Some functions were deprecated and enscriptem doesn't by default export ccall.

Oh, I didn't know about this... It must have been a recent change. I'll make sure to remove deprecated functions in my upcoming update. Thanks for letting me know.

PS: Any plans to put your project in GitHub pages? It will make it much easier to try!

**Comment by userlandkernel** [comment]
Yes it's very recent (v1.38.27: 02/10/2019) (https://github.com/emscripten-core/emscripten/pull/8011).
If you can help me place it on Github pages that would be awesome.
It doesn't depend on any network connection.
Was my first encounter with emscripten and I like it, but its a bit too young I guess.

**Comment by AlexAltea** [comment]
>  If you can help me place it on Github pages that would be awesome.

@userlandkernel You just need to enter your repository settings at:
https://github.com/userlandkernel/GandalfsMachotool/settings

Then search for "GitHub Pages", and in the field "Source" select the `master` branch. After few seconds/minutes, your website should be available for everyone here:
https://userlandkernel.github.io/GandalfsMachotool/macho.html

PS: If you rename `macho.html` to `index.html` it will be even easier to reach, and become just:
https://userlandkernel.github.io/GandalfsMachotool

**Comment by userlandkernel** [comment]
It's live.
Thanks for explaining :)

**Comment by AlexAltea** [comment]
I've fixed this issue by enabling `ALLOW_MEMORY_GROWTH` by default, and disabling `WASM` for now.
Though in the future, we should allow for asynchronous loading and re-enable WebAssembly.

Relevant commit: db42c8f26ed1c3392d7a3a7a6d21e949026fc42b.

**Comment by userlandkernel** [comment]
Great. Yeah WASM is way faster, must admit but for WASM to work we'll need to do some adaptations to the project ;)
Might take a look into that when I have time
